# Generated by Django 3.2.3 on 2021-08-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.category')),
            ],
        ),
    ]
