# Generated by Django 3.2.3 on 2021-08-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='urlName',
            field=models.CharField(default='defaultValue', max_length=300),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='urlName',
            field=models.CharField(default='defaultValue', max_length=300),
        ),
    ]
