# Generated by Django 3.2.3 on 2021-08-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0003_auto_20210813_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rank',
            field=models.FloatField(default=5),
        ),
    ]
