# Generated by Django 3.2.3 on 2021-12-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0005_productincategory_subcategoryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tagID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('tag', models.IntegerField()),
            ],
        ),
    ]
