# Generated by Django 3.2.3 on 2021-12-17 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0007_alter_tag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductWithTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.product')),
                ('tagID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.tag')),
            ],
        ),
    ]
