# Generated by Django 3.2.3 on 2021-12-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0008_productwithtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRatedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.product')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.user')),
            ],
        ),
    ]
