# Generated by Django 3.2.3 on 2021-12-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0009_userratedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratedproduct',
            name='rating',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
