# Generated by Django 3.2.10 on 2021-12-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webstore', '0010_userratedproduct_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='JointProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatedProducts', models.TextField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webstore.product')),
            ],
        ),
    ]
